project:
  type: website

website:
  title: "Júlia Gualberto"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/JuliaG1108
      - icon: instagram
        href: https://www.instagram.com/juliagualbeerto/?hl=pt-br
format:
  html:
    theme: flatly
    css: styles.css

editor: visual

